### ISSUE TITLE
Chat messages are displayed in reverse order

### ISSUE THREAD

**Issue by liconway** [farfar336/FunChat-application#31]
When sending messages to the chat (`#chatMessages`), the latest messages are added to the top of the list, not the bottom.

This is due to the usage of `flex-direction: column-reverse`

**Comment by farfar336** [comment]
> When sending messages to the chat (`#chatMessages`), the latest messages are added to the top of the list, not the bottom.
> 
> This is due to the usage of `flex-direction: column-reverse`

When I run the chat, I see new messages displayed at the bottom:
![image](https://user-images.githubusercontent.com/44077833/101114997-cf5d4300-359f-11eb-8c0f-14010cae9077.png)
Did you mean to say that latest messages are added to the bottom, not the top?

**Comment by farfar336** [comment]
> When sending messages to the chat (`#chatMessages`), the latest messages are added to the top of the list, not the bottom.

Would it be okay with you if we displayed the latest messages on the bottom, like in Assignment 3?

**Comment by liam-prod** [comment]
> > When sending messages to the chat (`#chatMessages`), the latest messages are added to the top of the list, not the bottom.
> 
> Would it be okay with you if we displayed the latest messages on the bottom, like in Assignment 3?

Yeah I figured that's how we wanted it, which is why I opened this issue. The `flex-direction: column-reverse` reverses the order of list items so the list item on the bottom of the DOM is displayed on the top, hence the latest messages displaying at the top.

I believe it was originally intended to put the list on the bottom of the screen, but the author didn't realize it also reverses the order of the list. This issue is open to essentially remove that CSS line and use a different method to move the list to the bottom of the page.

**Comment by farfar336** [comment]
> Yeah I figured that's how we wanted it, which is why I opened this issue. The flex-direction: column-reverse reverses the order of list items so the list item on the bottom of the DOM is displayed on the top, hence the latest messages displaying at the top.

> I believe it was originally intended to put the list on the bottom of the screen, but the author didn't realize it also reverses the order of the list. This issue is open to essentially remove that CSS line and use a different method to move the list to the bottom of the page.

I had the same problem with Assignment 3. I solved it by changing the order of how the messages were stored. So, if we have an array of 200 messages, the first element had the oldest message, and the 200th element had the latest message. The other way was to have the first element have the latest message, and the 200th element the oldest message. I can't remember which order solved the problem for me. You can try to both ways to see if that fixes it

**Comment by liam-prod** [comment]
The above fixes the issue using a container element

**Comment by farfar336** [comment]
Oh okay. Sara mentioned that she knows a way to fix the issue. So, we can merge it for now
